### ISSUE TITLE
`links` argument to docker/docker-compose is deprecated

### ISSUE THREAD

**Issue by maxalbert** [testdrivenio/testdriven-site#15]
See [here](https://docs.docker.com/compose/compose-file/#links).

This is used for example in [Part 1, Lesson 6](https://testdriven.io/part-one-postgres-setup) when the `users-db` service is added:
```yaml
services:

  users:

    [...]

    links:
      - users-db
```
I think it should be fine to simply remove the `links:` directive because docker-compose should automatically establish a network containing all services, which means that they can communicate between each other in the same way?
